import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
//@ts-ingore
import '@/app/globals.css'
import Header from '../components/Header';

import {Providers} from '@/components/providers/providerTheme';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body className={`${inter.className} transition-colors duration-500 ease-in-out bg-white dark:bg-gray-900 text-gray-800 dark:text-gray-100`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}
